# Fonte
font_family monospace
font_size 11.0

# Cursor
cursor_shape block
cursor_blink_interval 0
cursor #ff79c6

# Fundo (inspirado no wallpaper)
background #2b1e2f
foreground #eaeaf0
background_opacity 0.9

# Preto / base
color0 #1f1a24
color8 #4a3b52

# Vermelho / rosa
color1 #ff79c6
color9 #ff92d0

# Verde (mantido suave pra não quebrar estética)
color2 #8bd5ca
color10 #a6e3d0

# Amarelo (quase pastel)
color3 #f9e2af
color11 #fce8c8

# Azul
color4 #8be9fd
color12 #a6f0ff

# Magenta / roxo
color5 #bd93f9
color13 #d6b3ff

# Ciano
color6 #6ec1e4
color14 #9adfff

# Branco
color7 #eaeaf0
color15 #ffffff

# Padding
window_padding_width 6